### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by creage** [spmeesseman/vscode-taskexplorer#134]
I have installed v2.0.1, and I can not see any tasks now, and I see the error notification

`Maximum call stack size exceeded`

instead.

Reverting back to 1.29.0 fixes the issue.

**Comment by spmeesseman** [comment]
@creage - can u try 2.0.2 please?  and confirm if issue is corrected or not?  thanks!

**Comment by creage** [comment]
Still the same :(

![image](https://user-images.githubusercontent.com/910967/107929631-36bd4900-6f7a-11eb-9dc9-3ffa6eecf54e.png)

**Comment by spmeesseman** [comment]
shit,  if possible, if you can turn on the debug/logging in Task Explorer Settings, reproduce, and then send me the output found in the Task Explorer Output Window (i know, pain in the a**), I can look into this more after work today

**Comment by spmeesseman** [comment]
also, if u can, try turning off "group by separator" in the settings too, see if that fixes the 2.0.2 build too maybe

**Comment by spmeesseman** [comment]
one more thing you can try is to turn the grouping level setting down to maybe "1", instead of turning the "group by separator" setting off

**Comment by creage** [comment]
Here is the log. Changing on grouping didn't help.
 
[output.log](https://github.com/spmeesseman/vscode-taskexplorer/files/5980741/output.log)

**Comment by spmeesseman** [comment]
are you sure you turned off "group by separator" ?

i see this in the log...  (btw, thanks for helping out and sending the xtra info)

i got about 30 more minutes then gonna start work for the day if u can get back to me i still have a little time

**_2021-02-15 09:45:47.489       create task groupings by defined separator_**
2021-02-15 09:45:47.489          node name                      : powershell
2021-02-15 09:45:47.489          grouping level                 : 0
2021-02-15 09:45:47.489          is group                       : true
2021-02-15 09:45:47.489          file name                      : e2e-cypress/framework/powershell/
2021-02-15 09:45:47.489          folder                         : lerna
2021-02-15 09:45:47.489          path                           : e2e-cypress/framework/powershell/
2021-02-15 09:45:47.489       remove grouped tasks
2021-02-15 09:45:47.795 
2021-02-15 09:45:47.795 get tree children
2021-02-15 09:45:47.795    task folder                          : undefined
2021-02-15 09:45:47.795    all tasks need to be retrieved       : false
2021-02-15 09:45:47.795    specific tasks need to be retrieved  : false
2021-02-15 09:45:47.795    task tree needs to be built          : true
2021-02-15 09:45:47.795    waiting...
2021-02-15 09:45:47.905    waiting...
2021-02-15 09:45:48.126    waiting...
2021-02-15 09:45:48.236    waiting...
2021-02-15 09:45:48.348    waiting...

**Comment by creage** [comment]
Oh, I had to restart the VSCode to make these changes applied. Disabling grouping fixed the issue - now I can see my tasks!

**Comment by spmeesseman** [comment]
hmmm, try turning the enable sidebar setting off too, i see visibility events for sidebar/taskview which is weird for startup

**Comment by spmeesseman** [comment]
seems like a duplicate of #133 then.  can you start posting in that thread if you can get any more info to help try and track this down?  thanks!

**Comment by creage** [comment]
Well, I want to access my tasks fast, that's why I have the button on my sidebar

**Comment by spmeesseman** [comment]
there's a "explorer view" too in the Explorer, thats what I usually use.  the sidebar is an xtra click, its just got more space
